# Generated by Django 3.2.5 on 2021-07-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210730_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='1', max_length=255, unique=True),
        ),
    ]
