version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
#  pg_db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=1111
#      - POSTGRES_USER=curr
#      - POSTGRES_DB=bankcurr
##    volumes:
##      - pg_project:/var/lib/postgresql/data
#    ports:
#      - "5433:5433"
##  postgres
##  web
