version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  pg_db:
    image: postgres
    hostname: pg_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=curr
      - POSTGRES_DB=bankcurr
    volumes:
      - app_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - pg_db
        - redis
  worker:
      build: .
      command: celery -A devtest worker
      depends_on:
        - pg_db
        - redis
  beat:
    restart: always
    build: .
    command: celery -A devtest beat
    depends_on:
      - pg_db
      - redis

volumes:
  app_db: {}
