# Generated by Django 3.2.5 on 2021-08-02 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlfaBankUnAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата Курса Валют')),
                ('usd', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='USD')),
                ('rur', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='RUR')),
                ('eur', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='EUR')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'банк',
                'verbose_name_plural': 'банки',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'курсы',
                'verbose_name_plural': 'курсы валют',
            },
        ),
        migrations.CreateModel(
            name='AlfaBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=1, verbose_name='Дата')),
                ('eur_buy', models.FloatField(default=1, verbose_name='Покупка EUR')),
                ('eur_sell', models.FloatField(default=1, verbose_name='Продажа EUR')),
                ('usd_buy', models.FloatField(default=1, verbose_name='Покупка USD')),
                ('usd_sell', models.FloatField(default=1, verbose_name='Продажа USD')),
                ('rur_buy', models.FloatField(default=1, verbose_name='Покупка RUR')),
                ('rur_sell', models.FloatField(default=1, verbose_name='Продажа RUR')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bankcurrency.company', verbose_name='Банк')),
            ],
        ),
    ]
