# Generated by Django 3.2.5 on 2021-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BelarusBank',
        ),
        migrations.DeleteModel(
            name='NBRB',
        ),
        migrations.AlterModelOptions(
            name='alfabank',
            options={'verbose_name': ['title']},
        ),
        migrations.AddField(
            model_name='alfabank',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='date_upgrade',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='price_currency',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='title',
            field=models.CharField(default=None, max_length=150, verbose_name='Валюта'),
        ),
    ]
