# Generated by Django 3.2.5 on 2021-08-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0004_auto_20210809_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriorBank',
            new_name='BelBank',
        ),
        migrations.RenameModel(
            old_name='PriorBankUnAuth',
            new_name='BelBankUnAuth',
        ),
    ]
