# Generated by Django 3.2.5 on 2021-07-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0004_auto_20210727_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlfaBankUnAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата Курса Валют')),
                ('usd', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='USD')),
                ('rur', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='RUR')),
                ('eur', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='EUR')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'банк',
                'verbose_name_plural': 'банки',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'курсы',
                'verbose_name_plural': 'курсы валют',
            },
        ),
        migrations.RemoveField(
            model_name='alfabank',
            name='done',
        ),
        migrations.RemoveField(
            model_name='alfabank',
            name='eur',
        ),
        migrations.RemoveField(
            model_name='alfabank',
            name='rur',
        ),
        migrations.RemoveField(
            model_name='alfabank',
            name='title',
        ),
        migrations.RemoveField(
            model_name='alfabank',
            name='usd',
        ),
        migrations.AddField(
            model_name='alfabank',
            name='eur_buy',
            field=models.FloatField(default=1, verbose_name='Покупка EUR'),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='eur_sell',
            field=models.FloatField(default=1, verbose_name='Продажа EUR'),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='rur_buy',
            field=models.FloatField(default=1, verbose_name='Покупка RUR'),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='rur_sell',
            field=models.FloatField(default=1, verbose_name='Продажа RUR'),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='usd_buy',
            field=models.FloatField(default=1, verbose_name='Покупка USD'),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='usd_sell',
            field=models.FloatField(default=1, verbose_name='Продажа USD'),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bankcurrency.company', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='alfabank',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bankcurrency.date'),
        ),
    ]
