# Generated by Django 3.2.6 on 2021-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0005_auto_20210810_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alfabank',
            name='company',
        ),
        migrations.RemoveField(
            model_name='belapb',
            name='company',
        ),
        migrations.RemoveField(
            model_name='belbank',
            name='company',
        ),
        migrations.AlterField(
            model_name='alfabank',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
