# Generated by Django 3.2.5 on 2021-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0005_auto_20210729_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfabank',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
