# Generated by Django 3.2.5 on 2021-07-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0006_alter_alfabank_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfabank',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
