# Generated by Django 3.2.6 on 2021-08-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0008_alter_auth_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='company',
            field=models.CharField(choices=[('alfabank', 'Альфабанк'), ('belagrobank', 'Белагро'), ('belarusbank', 'Беларусбанк')], default='alfabank', max_length=255),
        ),
    ]
