# Generated by Django 3.2.6 on 2021-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0009_alter_auth_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='company',
            field=models.CharField(choices=[('АльфаБанк', 'Альфабанк'), ('БелАгроПромБанк', 'Белагропром'), ('БеларусБанк', 'Беларусбанк')], default='АльфаБанк', max_length=255),
        ),
        migrations.AlterField(
            model_name='unauth',
            name='company',
            field=models.CharField(choices=[('АльфаБанк', 'Альфабанк'), ('БелАгроПромБанк', 'Белагропром'), ('БеларусБанк', 'Беларусбанк')], default='АльфаБанк', max_length=255),
        ),
    ]
