# Generated by Django 3.2.6 on 2021-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0010_auto_20210816_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='eur_buy',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Покупка EUR'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='eur_sell',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Продажа EUR'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='rur_buy',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Покупка RUR'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='rur_sell',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Продажа RUR'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='usd_buy',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Покупка USD'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='usd_sell',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Продажа USD'),
        ),
        migrations.AlterField(
            model_name='unauth',
            name='usd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Продажа USD'),
        ),
    ]
