# Generated by Django 3.2.6 on 2021-09-02 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0013_auto_20210827_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('АльфаБанк', 'Альфабанк'), ('БелАгроПромБанк', 'Белагропром'), ('БеларусБанк', 'Беларусбанк')], max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Курса Валют')),
                ('eur_buy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Покупка EUR')),
                ('eur_sell', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Продажа EUR')),
                ('usd_buy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Покупка USD')),
                ('usd_sell', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Продажа USD')),
                ('rur_buy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Покупка RUR')),
                ('rur_sell', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Продажа RUR')),
            ],
            options={
                'verbose_name': 'currency',
                'db_table': 'currency_auth_user',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUnAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('АльфаБанк', 'Альфабанк'), ('БелАгроПромБанк', 'Белагропром'), ('БеларусБанк', 'Беларусбанк')], max_length=255)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата Курса Валют')),
                ('usd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Продажа USD')),
                ('rur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Продажа RUR')),
                ('eur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Продажа EUR')),
            ],
            options={
                'verbose_name': 'currency',
                'db_table': 'currency_un_auth_user',
            },
        ),
        migrations.DeleteModel(
            name='Auth',
        ),
        migrations.DeleteModel(
            name='UnAuth',
        ),
    ]
