# Generated by Django 3.2.6 on 2021-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0014_auto_20210902_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyauthuser',
            name='company',
            field=models.CharField(choices=[('Альфабанк', 'Альфабанк'), ('Белагропромбанк', 'Белагропром'), ('Беларусбанк', 'Беларусбанк')], max_length=255),
        ),
    ]
