# Generated by Django 3.2.6 on 2021-09-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcurrency', '0016_alter_currencyauthuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyunauthuser',
            name='company',
            field=models.CharField(choices=[('АльфаБанк', 'alfabank'), ('БелАгроПромБанк', 'Белагропром'), ('БеларусБанк', 'Беларусбанк')], max_length=255),
        ),
    ]
